# commons
logging:
        com.ssafy.api: debug
        com.ssafy.core: debug
        org.hibernate.type.descriptor.sql: trace
spring:
    profiles:
        active: local
        include:
            - core
    # server port number
    server:
        port: 8888
    jpa:
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        properties.hibernate:
            hbm2ddl.auto: update
            format_sql: true
            show_sql: true
            use_sql_comments: true
        generate-ddl: true
        open-in-view: false
    flyway:
        enabled: false
    config:
        activate:
            on-profile: local
